name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.ii.uib.no/"
        user: "sondreb"
        token: ${{ secrets.TOKEN }}
        job: "Githubjob"
