name: Trigger jenkins job
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Push to server
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.ii.uib.no/"
        user: "sondreb"
        token: ${{ secrets.TOKEN }}
        job: "Githubjob"
